# This is the network config written by 'subiquity'
network:
  version: 2
  ethernets:
    ens160:
      dhcp4: no
      dhcp6: no
      addresses: [10.0.5.12/24]
      routes:
        - to: default
          via: 10.0.5.2
      nameservers:
          addresses: [10.0.5.5]
          search: 
            - 'elizabeth.local'
